version: "3"

services:
  backend:
    build: ./
    ports:
      - 3001:3001
    environment:
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=todo_list
      - DB_HOST=db
      - JWT_SECRET=48kfjhd7uycxzjjcdsz67yczkj441a777
    volumes:
      - ./:/api-todolist
    container_name: api-todolist
    restart: always
    depends_on:
      - db
  
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    restart: always